# Sync to Google Cloud Storage

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ develop ]

#Variables
env:
  BUCKET: qlik_projects/
  PROJECT: ${{github.event.repository.name}}/
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 1
      - name: Create communication setup to Google Cloud Storage
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          
      # 2 
      #- name: Sync files to bucket Sync files to bucket
      #  run: gsutil -m rsync -R ./ gs://"$BUCKET"/"$PROJECT"
      
      # 2.1
      - name: Sync "2_Config" files to bucket 
        run: gsutil -m rsync -R ./2_Config gs://"$BUCKET""$PROJECT"2_Config     
      # 2.2
      - name: Sync "3_Include" files to bucket 
        run: gsutil -m rsync -R ./3_Include gs://"$BUCKET""$PROJECT"3_Include
      # 2.3
      - name: Sync "6_Misc" files to bucket 
        run: gsutil -m rsync -R ./6_Misc gs://"$BUCKET""$PROJECT"6_Misc  
        
      # 3 Upload files to create folders and update information
      # 3.1 Copy 1_QVD
      - name: Upload "1_QVD" files to bucket 
        run: gsutil  -m cp -r ./1_QVD gs://"$BUCKET""$PROJECT"
   
      # 3.2 Copy 4_Export
      - name: Upload "4_Export" files to bucket 
        run: gsutil  -m cp -r ./4_Export gs://"$BUCKET""$PROJECT"

      # 3.3 Copy 5_Import
      - name: Upload "5_Import" files to bucket 
        run: gsutil  -m cp -r ./5_Import gs://"$BUCKET""$PROJECT" 
        
      # 3.4 Copy "Info.txt"
      - name: Upload "Info.txt" file to bucket 
        run: gsutil  -m cp -r ./Info.txt gs://"$BUCKET""$PROJECT"
        
       # 3.5 Copy "Version.md"
      - name: Upload "Version.md" file to bucket 
        run: gsutil  -m cp -r ./Version.md gs://"$BUCKET""$PROJECT"    

       # 3.6 Copy "README.md"
      - name: Upload "README.md" file to bucket 
        run: gsutil  -m cp -r ./README.md gs://"$BUCKET""$PROJECT"    
        
      # 4 Cache
      # 4.1
      - name: Set cache-control for qlik files
        run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store"  gs://"$BUCKET""$PROJECT"**/*.{.qvd,.qvs,.qvf}
        
      # 4.2
      # - name: Set cache-control for static files for 1 hour
      #  run: gsutil -m setmeta -h "Cache-Control:public, max-age=1800"  gs://"$BUCKET""$PROJECT"**/*.{.qvf}
            
      # 5 Access
      #- name: Allow public access
      #  run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET""$PROJECT"
